/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chiller.gltf 
Author: issiih (https://sketchfab.com/issiih)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chiller-r2-dda10936768f489d84f7f6edeb30effb
Title: Chiller_R2
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Chiller(props) {
  const { nodes, materials } = useGLTF("/chiller.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -0.001, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["Cylinder_Baked.001"]}
            scale={[1, 1, 4.5]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["Plane_Baked.001"]}
            position={[0, 0, 4.5]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials["Cylinder.001_Baked.001"]}
            position={[-2.092, 0.418, 0]}
            scale={[0.819, 0.819, 4.5]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials["Cylinder.002_Baked.001"]}
            position={[0, 0, 0.029]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials["Cylinder.003_Baked.001"]}
            position={[-2.092, 0.418, 0.029]}
            scale={[0.823, 0.823, 1]}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials["Plane.001_Baked.001"]}
            position={[0, 0, -4.5]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials["Cube.001_Baked.001"]}
            position={[0.971, 1.976, -0.617]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.333, 0.786, 1.132]}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials["Cube.002_Baked.001"]}
            position={[0.765, 2.057, 1.762]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials["Plane.002_Baked.001"]}
            position={[-2.092, 1.49, 1.216]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials["Sphere_Baked.001"]}
            position={[-2.092, 2.49, 0.322]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.65, 0.529, 0.65]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials["Sphere.001_Baked.001"]}
            position={[-2.092, 2.49, 0.322]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.65, 0.529, 0.65]}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials["Sphere.002_Baked.001"]}
            position={[-2.092, 2.49, -0.646]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.65, 0.529, 0.65]}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials["Plane.003_Baked.001"]}
            position={[-0.445, 0.834, 1.216]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials["Plane.004_Baked.001"]}
            position={[-0.445, 0.667, -1.934]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials["Cylinder.004_Baked.001"]}
            position={[-0.445, 2.031, -0.338]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.455, 1.033, 0.455]}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials["Cylinder.005_Baked.001"]}
            position={[-1.793, 2.031, -2.616]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.349, 0.271, 0.349]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials["YORK_Baked.001"]}
            position={[1.376, 3.288, 2.625]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.213}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials["Circle_Baked.001"]}
            position={[1.387, 3.243, 1.948]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials["Cylinder.006_Baked.001"]}
            position={[1.385, 3.068, 2.6]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.029, 0.01, 0.029]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials["Cylinder.007_Baked.001"]}
            position={[1.385, 3.068, 2.791]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.029, 0.01, 0.029]}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials["Cylinder.008_Baked.001"]}
            position={[1.385, 3.068, 2.415]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.029, 0.01, 0.029]}
          />
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials["Cube_Baked.001"]}
            position={[1.376, 1.711, 2.827]}
            scale={0.885}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials["Cube.004_Baked.001"]}
            position={[1.406, 2.553, 2.628]}
            scale={[0.031, 0.12, 0.12]}
          />
          <mesh
            geometry={nodes.Object_50.geometry}
            material={materials["Cube.005_Baked.001"]}
            position={[1.062, 3.733, 2.641]}
            scale={0.885}
          />
          <mesh
            geometry={nodes.Object_52.geometry}
            material={materials["Cube.006_Baked.001"]}
            position={[0.931, 3.733, 0.688]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.885, 0.885, 0.741]}
          />
          <mesh
            geometry={nodes.Object_54.geometry}
            material={materials["Circle.001_Baked.001"]}
            position={[1.416, 1.551, -0.617]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.081}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials["Circle.002_Baked.001"]}
            position={[1.416, 1.551, -0.617]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.081}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials["Circle.004_Baked.001"]}
            position={[1.329, 2.754, -1.251]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_60.geometry}
            material={materials["Circle.005_Baked.001"]}
            position={[1.329, 1.191, -1.251]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials["Cylinder.009_Baked.001"]}
            position={[0, 0, 0.029]}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials["Cylinder.010_Baked.001"]}
            position={[-2.092, 0.418, 0]}
          />
          <mesh
            geometry={nodes.Object_66.geometry}
            material={materials["Cylinder.011_Baked.001"]}
            position={[-2.092, 2.49, -1.145]}
            scale={0.826}
          />
          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials["Cylinder.012_Baked.001"]}
            position={[-2.092, 2.49, -1.324]}
            scale={0.826}
          />
          <mesh
            geometry={nodes.Object_70.geometry}
            material={materials["Cylinder.013_Baked.001"]}
            position={[-2.092, 2.49, -2.33]}
            scale={0.579}
          />
          <mesh
            geometry={nodes.Object_72.geometry}
            material={materials["Cylinder.014_Baked.001"]}
            position={[-2.092, 2.49, -2.237]}
            scale={0.579}
          />
          <mesh
            geometry={nodes.Object_74.geometry}
            material={materials["Cylinder.015_Baked.001"]}
            position={[-0.445, 2.031, -1.211]}
            scale={0.622}
          />
          <mesh
            geometry={nodes.Object_76.geometry}
            material={materials["Cylinder.016_Baked.001"]}
            position={[-0.445, 2.031, -0.893]}
            scale={0.622}
          />
          <mesh
            geometry={nodes.Object_78.geometry}
            material={materials["Plane.005_Baked.001"]}
            position={[-2.667, 1.49, 0.615]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Object_80.geometry}
            material={materials["Plane.006_Baked.001"]}
            position={[-0.445, 2.031, -0.338]}
          />
          <mesh
            geometry={nodes.Object_82.geometry}
            material={materials["Cylinder.017_Baked.001"]}
            position={[0.278, 1.071, 3.657]}
          />
          <mesh
            geometry={nodes.Object_84.geometry}
            material={materials["Cylinder.018_Baked.001"]}
            position={[-2.04, 1.333, -3.531]}
          />
          <mesh
            geometry={nodes.Object_86.geometry}
            material={materials["Sphere.003_Baked.001"]}
            position={[0.906, 0.69, -2.296]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chiller.gltf");
